/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'time' : IDL.Int,
  'sender' : IDL.Text,
});
export const Scenario = IDL.Record({ 'title' : IDL.Text, 'prompt' : IDL.Text });
export const Session = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'analysisSummary' : IDL.Text,
  'endTime' : IDL.Opt(IDL.Int),
  'messages' : IDL.Vec(Message),
  'scenario' : Scenario,
  'confidenceScores' : IDL.Vec(IDL.Float64),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Progress = IDL.Record({
  'allSessions' : IDL.Vec(Session),
  'averageConfidence' : IDL.Float64,
  'sessionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Session], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSessions' : IDL.Func([], [], []),
  'createSession' : IDL.Func([Scenario], [Session], []),
  'endSession' : IDL.Func([IDL.Text, IDL.Text], [Session], []),
  'getAnalysisSummaries' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProgressStats' : IDL.Func([], [Progress], ['query']),
  'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
  'getSessionHistory' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getSessionOwner' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
  'getSessionSummaries' : IDL.Func(
      [],
      [IDL.Record({ 'messages' : IDL.Nat, 'summaries' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'time' : IDL.Int,
    'sender' : IDL.Text,
  });
  const Scenario = IDL.Record({ 'title' : IDL.Text, 'prompt' : IDL.Text });
  const Session = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'analysisSummary' : IDL.Text,
    'endTime' : IDL.Opt(IDL.Int),
    'messages' : IDL.Vec(Message),
    'scenario' : Scenario,
    'confidenceScores' : IDL.Vec(IDL.Float64),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Progress = IDL.Record({
    'allSessions' : IDL.Vec(Session),
    'averageConfidence' : IDL.Float64,
    'sessionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Session], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSessions' : IDL.Func([], [], []),
    'createSession' : IDL.Func([Scenario], [Session], []),
    'endSession' : IDL.Func([IDL.Text, IDL.Text], [Session], []),
    'getAnalysisSummaries' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProgressStats' : IDL.Func([], [Progress], ['query']),
    'getScenarios' : IDL.Func([], [IDL.Vec(Scenario)], ['query']),
    'getSessionHistory' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getSessionOwner' : IDL.Func([IDL.Text], [IDL.Principal], ['query']),
    'getSessionSummaries' : IDL.Func(
        [],
        [IDL.Record({ 'messages' : IDL.Nat, 'summaries' : IDL.Nat })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };