/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'content' : string,
  'time' : bigint,
  'sender' : string,
}
export interface Progress {
  'allSessions' : Array<Session>,
  'averageConfidence' : number,
  'sessionCount' : bigint,
}
export interface Scenario { 'title' : string, 'prompt' : string }
export interface Session {
  'id' : string,
  'startTime' : bigint,
  'analysisSummary' : string,
  'endTime' : [] | [bigint],
  'messages' : Array<Message>,
  'scenario' : Scenario,
  'confidenceScores' : Array<number>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, string, string], Session>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearSessions' : ActorMethod<[], undefined>,
  'createSession' : ActorMethod<[Scenario], Session>,
  'endSession' : ActorMethod<[string, string], Session>,
  'getAnalysisSummaries' : ActorMethod<[], Array<[string, string]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProgressStats' : ActorMethod<[], Progress>,
  'getScenarios' : ActorMethod<[], Array<Scenario>>,
  'getSessionHistory' : ActorMethod<[], Array<Session>>,
  'getSessionOwner' : ActorMethod<[string], Principal>,
  'getSessionSummaries' : ActorMethod<
    [],
    { 'messages' : bigint, 'summaries' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSessions' : ActorMethod<[], Array<Session>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];